services:
  searcharr:
    container_name: searcharr
    image: toddrob/searcharr:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./settings.py:/app/settings.py
    environment:
      - TZ=Europe/Dublin
    restart: unless-stopped
    network_mode: host
